#! /bin/sh

dir=`dirname $0`

uname_s=`uname -s`

case $uname_s in
   FreeBSD) sed=gsed ;;
   *) sed=sed ;;
esac

$dir/../../memcheck/tests/filter_xml |

# Perform Solaris-specific filtering (see filter_stderr_solaris).
if $dir/../../tests/os_test solaris; then
   $sed -e 's/mutex_unlock/pthread_mutex_unlock/'
else
   cat
fi
