Syscall param posix_fallocate(offset_low) contains uninitialised byte(s)
   at 0x........: posix_fallocate (in /...libc...)
   by 0x........: main (posix_fallocate.c:13)

Syscall param posix_fallocate(offset_high) contains uninitialised byte(s)
   at 0x........: posix_fallocate (in /...libc...)
   by 0x........: main (posix_fallocate.c:13)

Syscall param posix_fallocate(MERGE_FIRST(len)) contains uninitialised byte(s)
   at 0x........: posix_fallocate (in /...libc...)
   by 0x........: main (posix_fallocate.c:14)

Syscall param posix_fallocate(MERGE_SECOND(len)) contains uninitialised byte(s)
   at 0x........: posix_fallocate (in /...libc...)
   by 0x........: main (posix_fallocate.c:14)

