Syscall param posix_fallocate(offset_low) contains uninitialised byte(s)
   at 0x........: posix_fallocate (in /...libc...)
   ...

Syscall param posix_fallocate(offset_high) contains uninitialised byte(s)
   at 0x........: posix_fallocate (in /...libc...)
   ...

Syscall param posix_fallocate(MERGE_FIRST(len)) contains uninitialised byte(s)
   at 0x........: posix_fallocate (in /...libc...)
   ...

Syscall param posix_fallocate(MERGE_SECOND(len)) contains uninitialised byte(s)
   at 0x........: posix_fallocate (in /...libc...)
   ...

