WARNING: Valgrind may not operate correctly in capability mode.
         Please consider disabling capability by using the RUNNING_ON_VALGRIND mechanism.
         See http://valgrind.org/docs/manual/manual-core-adv.html#manual-core-adv.clientreq
Syscall param cap_getmode(modep) points to unaddressable byte(s)
   ...
   by 0x........: main (capsicum.c:56)
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param cap_rights_get(rights) points to unaddressable byte(s)
   ...
   by 0x........: main (capsicum.c:58)
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param cap_rights_get(fd) contains uninitialised byte(s)
   ...
   by 0x........: main (capsicum.c:59)

Syscall param cap_rights_get(rights) points to unaddressable byte(s)
   ...
   by 0x........: main (capsicum.c:63)
 Address 0x........ is 0 bytes inside a block of size 16 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (capsicum.c:62)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (capsicum.c:60)

Syscall param cap_rights_limit(fd) contains uninitialised byte(s)
   ...
   by 0x........: main (capsicum.c:65)

Syscall param cap_rights_limit(rights) points to unaddressable byte(s)
   ...
   by 0x........: main (capsicum.c:67)
 Address 0x........ is 0 bytes inside a block of size 16 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (capsicum.c:62)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (capsicum.c:60)

