Syscall param linkat(name1) points to unaddressable byte(s)
   at 0x........: linkat (in /...libc...)
   by 0x........: main (linkat.c:53)
 Address 0x........ is 0 bytes inside a block of size 19 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (linkat.c:52)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   ...
   by 0x........: main (linkat.c:51)

Syscall param symlinkat(name1) points to unaddressable byte(s)
   at 0x........: symlinkat (in /...libc...)
   by 0x........: main (linkat.c:54)
 Address 0x........ is 0 bytes inside a block of size 19 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (linkat.c:52)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   ...
   by 0x........: main (linkat.c:51)

Syscall param linkat(name2) points to unaddressable byte(s)
   at 0x........: linkat (in /...libc...)
   by 0x........: main (linkat.c:60)
 Address 0x........ is 0 bytes inside a block of size 19 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (linkat.c:59)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   ...
   by 0x........: main (linkat.c:58)

Syscall param unlinkat(path) points to unaddressable byte(s)
   at 0x........: unlinkat (in /...libc...)
   by 0x........: main (linkat.c:61)
 Address 0x........ is 0 bytes inside a block of size 19 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (linkat.c:59)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   ...
   by 0x........: main (linkat.c:58)

Syscall param symlinkat(name2) points to unaddressable byte(s)
   at 0x........: symlinkat (in /...libc...)
   by 0x........: main (linkat.c:65)
 Address 0x........ is 0 bytes inside a block of size 19 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (linkat.c:64)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   ...
   by 0x........: main (linkat.c:63)

Syscall param unlinkat(path) points to unaddressable byte(s)
   at 0x........: unlinkat (in /...libc...)
   by 0x........: main (linkat.c:66)
 Address 0x........ is 0 bytes inside a block of size 19 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (linkat.c:64)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   ...
   by 0x........: main (linkat.c:63)

Syscall param linkat(fd1) contains uninitialised byte(s)
   at 0x........: linkat (in /...libc...)
   by 0x........: main (linkat.c:69)

Syscall param linkat(fd2) contains uninitialised byte(s)
   at 0x........: linkat (in /...libc...)
   by 0x........: main (linkat.c:69)

Syscall param linkat(flag) contains uninitialised byte(s)
   at 0x........: linkat (in /...libc...)
   by 0x........: main (linkat.c:69)

Syscall param symlinkat(fd) contains uninitialised byte(s)
   at 0x........: symlinkat (in /...libc...)
   by 0x........: main (linkat.c:70)

Syscall param unlinkat(fd) contains uninitialised byte(s)
   at 0x........: unlinkat (in /...libc...)
   by 0x........: main (linkat.c:71)

Syscall param unlinkat(flag) contains uninitialised byte(s)
   at 0x........: unlinkat (in /...libc...)
   by 0x........: main (linkat.c:71)

Syscall param fdatasync(fd) contains uninitialised byte(s)
   ...
   by 0x........: main (linkat.c:78)

