Syscall param linkat(name1) points to unaddressable byte(s)
   at 0x........: linkat (in /...libc...)
   by 0x........: main (linkat.c:49)
 Address 0x........ is 0 bytes inside a block of size 19 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (linkat.c:48)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   ...
   by 0x........: main (linkat.c:47)

Syscall param symlinkat(name1) points to unaddressable byte(s)
   at 0x........: symlinkat (in /...libc...)
   by 0x........: main (linkat.c:50)
 Address 0x........ is 0 bytes inside a block of size 19 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (linkat.c:48)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   ...
   by 0x........: main (linkat.c:47)

Syscall param linkat(name2) points to unaddressable byte(s)
   at 0x........: linkat (in /...libc...)
   by 0x........: main (linkat.c:56)
 Address 0x........ is 0 bytes inside a block of size 19 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (linkat.c:55)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   ...
   by 0x........: main (linkat.c:54)

Syscall param unlinkat(path) points to unaddressable byte(s)
   at 0x........: unlinkat (in /...libc...)
   by 0x........: main (linkat.c:57)
 Address 0x........ is 0 bytes inside a block of size 19 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (linkat.c:55)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   ...
   by 0x........: main (linkat.c:54)

Syscall param symlinkat(name2) points to unaddressable byte(s)
   at 0x........: symlinkat (in /...libc...)
   by 0x........: main (linkat.c:61)
 Address 0x........ is 0 bytes inside a block of size 19 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (linkat.c:60)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   ...
   by 0x........: main (linkat.c:59)

Syscall param unlinkat(path) points to unaddressable byte(s)
   at 0x........: unlinkat (in /...libc...)
   by 0x........: main (linkat.c:62)
 Address 0x........ is 0 bytes inside a block of size 19 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (linkat.c:60)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   ...
   by 0x........: main (linkat.c:59)

Syscall param linkat(fd1) contains uninitialised byte(s)
   at 0x........: linkat (in /...libc...)
   by 0x........: main (linkat.c:65)

Syscall param linkat(fd2) contains uninitialised byte(s)
   at 0x........: linkat (in /...libc...)
   by 0x........: main (linkat.c:65)

Syscall param linkat(flag) contains uninitialised byte(s)
   at 0x........: linkat (in /...libc...)
   by 0x........: main (linkat.c:65)

Syscall param symlinkat(fd) contains uninitialised byte(s)
   at 0x........: symlinkat (in /...libc...)
   by 0x........: main (linkat.c:66)

Syscall param unlinkat(fd) contains uninitialised byte(s)
   at 0x........: unlinkat (in /...libc...)
   by 0x........: main (linkat.c:67)

