---------------------------------------------------------
  1:                SYS_exit below
---------------------------------------------------------
---------------------------------------------------------
  2:                SYS_fork @todo
---------------------------------------------------------
---------------------------------------------------------
  3:                SYS_read 1+3s 0m
---------------------------------------------------------
Syscall param (syscallno) contains uninitialised byte(s)
   ...

Syscall param read(buf) contains uninitialised byte(s)
   ...

Syscall param read(count) contains uninitialised byte(s)
   ...

Syscall param read(buf) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
  4:               SYS_write 3s 1m
---------------------------------------------------------
Syscall param write(fd) contains uninitialised byte(s)
   ...

Syscall param write(buf) contains uninitialised byte(s)
   ...

Syscall param write(count) contains uninitialised byte(s)
   ...

Syscall param write(buf) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
  5:                SYS_open (2-args) 2s 1m
---------------------------------------------------------
Syscall param open(filename) contains uninitialised byte(s)
   ...

Syscall param open(flags) contains uninitialised byte(s)
   ...

Syscall param open(filename) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
  5:                SYS_open (3-args) 1s 0m
---------------------------------------------------------
Syscall param open(mode) contains uninitialised byte(s)
   ...

---------------------------------------------------------
  6:               SYS_close 1s 0m
---------------------------------------------------------
Syscall param close(fd) contains uninitialised byte(s)
   ...

---------------------------------------------------------
  7:               SYS_wait4 4s 2m
---------------------------------------------------------
Syscall param wait4(pid) contains uninitialised byte(s)
   ...

Syscall param wait4(status) contains uninitialised byte(s)
   ...

Syscall param wait4(options) contains uninitialised byte(s)
   ...

Syscall param wait4(rusage) contains uninitialised byte(s)
   ...

Syscall param wait4(status) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param wait4(rusage) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
  9:                SYS_link 2s 2m
---------------------------------------------------------
Syscall param link(oldpath) contains uninitialised byte(s)
   ...

Syscall param link(newpath) contains uninitialised byte(s)
   ...

Syscall param link(oldpath) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param link(newpath) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 10:              SYS_unlink 1s 1m
---------------------------------------------------------
Syscall param unlink(pathname) contains uninitialised byte(s)
   ...

Syscall param unlink(pathname) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 12:               SYS_chdir 1s 1m
---------------------------------------------------------
Syscall param chdir(path) contains uninitialised byte(s)
   ...

Syscall param chdir(path) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 13:              SYS_fchdir 1s 0m
---------------------------------------------------------
Syscall param fchdir(fd) contains uninitialised byte(s)
   ...

---------------------------------------------------------
 14:     SYS_freebsd11_mknod 3s 1m
---------------------------------------------------------
Syscall param mknod(pathname) contains uninitialised byte(s)
   ...

Syscall param mknod(mode) contains uninitialised byte(s)
   ...

Syscall param mknod(dev) contains uninitialised byte(s)
   ...

Syscall param mknod(pathname) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 15:               SYS_chmod 2s 1m
---------------------------------------------------------
Syscall param chmod(path) contains uninitialised byte(s)
   ...

Syscall param chmod(mode) contains uninitialised byte(s)
   ...

Syscall param chmod(path) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 16:               SYS_chown 3s 1m
---------------------------------------------------------
Syscall param chown(path) contains uninitialised byte(s)
   ...

Syscall param chown(owner) contains uninitialised byte(s)
   ...

Syscall param chown(group) contains uninitialised byte(s)
   ...

Syscall param chown(path) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 17:               SYS_break ni
---------------------------------------------------------
---------------------------------------------------------
 20:              SYS_getpid 0s 0m
---------------------------------------------------------
---------------------------------------------------------
 21:               SYS_mount 4s 2m
---------------------------------------------------------
Syscall param mount(type) contains uninitialised byte(s)
   ...

Syscall param mount(path) contains uninitialised byte(s)
   ...

Syscall param mount(flags) contains uninitialised byte(s)
   ...

Syscall param mount(data) contains uninitialised byte(s)
   ...

Syscall param mount(type) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param mount(path) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 22:             SYS_unmount 1s 1m
---------------------------------------------------------
Syscall param unmount(path) contains uninitialised byte(s)
   ...

Syscall param unmount(path) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 23:              SYS_setuid 1s 0m
---------------------------------------------------------
Syscall param setuid(uid) contains uninitialised byte(s)
   ...

---------------------------------------------------------
 24:              SYS_getuid 0s 0m
---------------------------------------------------------
---------------------------------------------------------
 25:             SYS_geteuid 0s 0m
---------------------------------------------------------
---------------------------------------------------------
 26:              SYS_ptrace 4s 0m
---------------------------------------------------------
Syscall param ptrace(request) contains uninitialised byte(s)
   ...

Syscall param ptrace(pid) contains uninitialised byte(s)
   ...

Syscall param ptrace(addr) contains uninitialised byte(s)
   ...

Syscall param ptrace(data) contains uninitialised byte(s)
   ...

---------------------------------------------------------
 27:             SYS_recvmsg 3s 0m
---------------------------------------------------------
Syscall param recvmsg(s) contains uninitialised byte(s)
   ...

Syscall param recvmsg(msg) contains uninitialised byte(s)
   ...

Syscall param recvmsg(flags) contains uninitialised byte(s)
   ...

---------------------------------------------------------
 28:             SYS_sendmsg 3s 0m
---------------------------------------------------------
Syscall param sendmsg(s) contains uninitialised byte(s)
   ...

Syscall param sendmsg(msg) contains uninitialised byte(s)
   ...

Syscall param sendmsg(flags) contains uninitialised byte(s)
   ...

---------------------------------------------------------
 29:            SYS_recvfrom 5s 0m
---------------------------------------------------------
Syscall param recvfrom(s) contains uninitialised byte(s)
   ...

Syscall param recvfrom(buf) contains uninitialised byte(s)
   ...

Syscall param recvfrom(len) contains uninitialised byte(s)
   ...

Syscall param recvfrom(flags) contains uninitialised byte(s)
   ...

Syscall param recvfrom(from) contains uninitialised byte(s)
   ...

---------------------------------------------------------
 30:              SYS_accept 3s 0m
---------------------------------------------------------
Syscall param accept(s) contains uninitialised byte(s)
   ...

Syscall param accept(addr) contains uninitialised byte(s)
   ...

Syscall param accept(*addrlen) contains uninitialised byte(s)
   ...

---------------------------------------------------------
 31:         SYS_getpeername 3s 1m
---------------------------------------------------------
Syscall param getpeername(s) contains uninitialised byte(s)
   ...

Syscall param getpeername(name) contains uninitialised byte(s)
   ...

Syscall param getpeername(namelen) contains uninitialised byte(s)
   ...

Syscall param socketcall.getpeername(namelen_in) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 32:         SYS_getsockname 3s 1m
---------------------------------------------------------
Syscall param getsockname(s) contains uninitialised byte(s)
   ...

Syscall param getsockname(name) contains uninitialised byte(s)
   ...

Syscall param getsockname(namelen) contains uninitialised byte(s)
   ...

Syscall param socketcall.getsockname(namelen_in) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 25:             SYS_geteuid 0s 0m
---------------------------------------------------------
---------------------------------------------------------
 34:             SYS_chflags 2s 1m
---------------------------------------------------------
Syscall param chflags(path) contains uninitialised byte(s)
   ...

Syscall param chflags(flags) contains uninitialised byte(s)
   ...

Syscall param chflags(path) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 35:            SYS_fchflags 2s 0m
---------------------------------------------------------
Syscall param fchflags(fd) contains uninitialised byte(s)
   ...

Syscall param fchflags(flags) contains uninitialised byte(s)
   ...

---------------------------------------------------------
 36:                SYS_sync 0s 0m
---------------------------------------------------------
---------------------------------------------------------
 37:                SYS_kill 2s 0m
---------------------------------------------------------
Syscall param kill(pid) contains uninitialised byte(s)
   ...

Syscall param kill(signal) contains uninitialised byte(s)
   ...

---------------------------------------------------------
 39:             SYS_getppid 0s 0m
---------------------------------------------------------
---------------------------------------------------------
 41:                 SYS_dup 1s 0m
---------------------------------------------------------
Syscall param dup(oldfd) contains uninitialised byte(s)
   ...

---------------------------------------------------------
 42:      SYS_freebsd10_pipe 0s 0m
---------------------------------------------------------
---------------------------------------------------------
 43:             SYS_getegid 0s 0m
---------------------------------------------------------
---------------------------------------------------------
 44:              SYS_profil ni
---------------------------------------------------------
---------------------------------------------------------
 45:              SYS_ktrace ni
---------------------------------------------------------
---------------------------------------------------------
 47:              SYS_getgid 0s 0m
---------------------------------------------------------
---------------------------------------------------------
 49:            SYS_getlogin 2s 1m
---------------------------------------------------------
Syscall param getlogin(buf) contains uninitialised byte(s)
   ...

Syscall param getlogin(len) contains uninitialised byte(s)
   ...

Syscall param getlogin(name) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 50:            SYS_setlogin 1s 1m
---------------------------------------------------------
Syscall param setlogin(buf) contains uninitialised byte(s)
   ...

Syscall param setlogin(buf) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 51:                SYS_acct 1s 1m
---------------------------------------------------------
Syscall param acct(filename) contains uninitialised byte(s)
   ...

Syscall param acct(filename) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 53:         SYS_sigaltstack 2s 2m
---------------------------------------------------------
Syscall param sigaltstack(ss) contains uninitialised byte(s)
   ...

Syscall param sigaltstack(oss) contains uninitialised byte(s)
   ...

Syscall param sigaltstack(ss) points to unaddressable byte(s)
   ...
 Address 0x........ is on thread 1's stack

Syscall param sigaltstack(oss) points to unaddressable byte(s)
   ...
 Address 0x........ is on thread 1's stack

Conditional jump or move depends on uninitialised value(s)
   ...

---------------------------------------------------------
 54:               SYS_ioctl 3s 1m
---------------------------------------------------------
Syscall param ioctl(fd) contains uninitialised byte(s)
   ...

Syscall param ioctl(request) contains uninitialised byte(s)
   ...

Syscall param ioctl(arg) contains uninitialised byte(s)
   ...

Syscall param ioctl(generic) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 56:              SYS_revoke 1s 1m
---------------------------------------------------------
Syscall param revoke(path) contains uninitialised byte(s)
   ...

Syscall param revoke(path) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 57:             SYS_symlink 2s 2m
---------------------------------------------------------

More than 100 errors detected.  Subsequent errors
will still be recorded, but in less detail than before.
Syscall param symlink(oldpath) contains uninitialised byte(s)
   ...

Syscall param symlink(newpath) contains uninitialised byte(s)
   ...

Syscall param symlink(oldpath) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param symlink(newpath) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 58:            SYS_readlink 3s 2m
---------------------------------------------------------
Syscall param readlink(path) contains uninitialised byte(s)
   ...

Syscall param readlink(buf) contains uninitialised byte(s)
   ...

Syscall param readlink(bufsiz) contains uninitialised byte(s)
   ...

Syscall param readlink(path) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param readlink(buf) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 59:              SYS_execve 3s 1m
---------------------------------------------------------
Syscall param execve(filename) contains uninitialised byte(s)
   ...

Syscall param execve(argv) contains uninitialised byte(s)
   ...

Syscall param execve(envp) contains uninitialised byte(s)
   ...

Syscall param execve(filename) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 60:               SYS_umask 1s 0m
---------------------------------------------------------
Syscall param umask(mask) contains uninitialised byte(s)
   ...

---------------------------------------------------------
 61:              SYS_chroot 1s 1m
---------------------------------------------------------
Syscall param chroot(path) contains uninitialised byte(s)
   ...

Syscall param chroot(path) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 65:               SYS_msync 3s 1m
---------------------------------------------------------
Syscall param msync(start) contains uninitialised byte(s)
   ...

Syscall param msync(length) contains uninitialised byte(s)
   ...

Syscall param msync(flags) contains uninitialised byte(s)
   ...

Syscall param msync(start) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 66:               SYS_vfork other
---------------------------------------------------------
---------------------------------------------------------
 69:                SYS_sbrk 1s 1m
---------------------------------------------------------
Syscall param sbrk(incr) contains uninitialised byte(s)
   ...

---------------------------------------------------------
 73:              SYS_munmap 2s 0m
---------------------------------------------------------
Syscall param munmap(start) contains uninitialised byte(s)
   ...

Syscall param munmap(length) contains uninitialised byte(s)
   ...

---------------------------------------------------------
 74:            SYS_mprotect 3s 0m
---------------------------------------------------------
Syscall param mprotect(addr) contains uninitialised byte(s)
   ...

Syscall param mprotect(len) contains uninitialised byte(s)
   ...

Syscall param mprotect(prot) contains uninitialised byte(s)
   ...

---------------------------------------------------------
 75:             SYS_madvise 3s 0m
---------------------------------------------------------
Syscall param madvise(start) contains uninitialised byte(s)
   ...

Syscall param madvise(length) contains uninitialised byte(s)
   ...

Syscall param madvise(advice) contains uninitialised byte(s)
   ...

---------------------------------------------------------
 78:             SYS_mincore 3s 1m
---------------------------------------------------------
Syscall param mincore(start) contains uninitialised byte(s)
   ...

Syscall param mincore(length) contains uninitialised byte(s)
   ...

Syscall param mincore(vec) contains uninitialised byte(s)
   ...

Syscall param mincore(vec) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 79:           SYS_getgroups 2s 1m
---------------------------------------------------------
Syscall param getgroups(size) contains uninitialised byte(s)
   ...

Syscall param getgroups(list) contains uninitialised byte(s)
   ...

Syscall param getgroups(list) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 80:           SYS_setgroups 2s 1m
---------------------------------------------------------
Syscall param setgroups(size) contains uninitialised byte(s)
   ...

Syscall param setgroups(list) contains uninitialised byte(s)
   ...

Syscall param setgroups(list) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 81:             SYS_getpgrp 0s 0m
---------------------------------------------------------
---------------------------------------------------------
 82:             SYS_setpgid 2s 0m
---------------------------------------------------------
Syscall param setpgid(pid) contains uninitialised byte(s)
   ...

Syscall param setpgid(pgid) contains uninitialised byte(s)
   ...

---------------------------------------------------------
 83:           SYS_setitimer 3s 2m
---------------------------------------------------------
Syscall param setitimer(which) contains uninitialised byte(s)
   ...

Syscall param setitimer(value) contains uninitialised byte(s)
   ...

Syscall param setitimer(ovalue) contains uninitialised byte(s)
   ...

Syscall param setitimer(&value->it_interval) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param setitimer(&value->it_value) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param setitimer(&ovalue->it_interval) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param setitimer(&ovalue->it_value) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 85:              SYS_swapon 1s 1m
---------------------------------------------------------
Syscall param swapon(special) contains uninitialised byte(s)
   ...

Syscall param swapon(special) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 86:           SYS_getitimer 2s 1m
---------------------------------------------------------
Syscall param getitimer(which) contains uninitialised byte(s)
   ...

Syscall param getitimer(value) contains uninitialised byte(s)
   ...

Syscall param getitimer(&value->it_interval) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param getitimer(&value->it_value) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 89:       SYS_getdtablesize 0s 0m
---------------------------------------------------------
---------------------------------------------------------
 90:                SYS_dup2 2s 0m
---------------------------------------------------------
Syscall param dup2(oldfd) contains uninitialised byte(s)
   ...

Syscall param dup2(newfd) contains uninitialised byte(s)
   ...

---------------------------------------------------------
 92:               SYS_fcntl (GETFD) 2s 0m
---------------------------------------------------------
Syscall param fcntl(fd) contains uninitialised byte(s)
   ...

Syscall param fcntl(cmd) contains uninitialised byte(s)
   ...

---------------------------------------------------------
 92:               SYS_fcntl (DUPFD) 1s 0m
---------------------------------------------------------
Syscall param fcntl(arg) contains uninitialised byte(s)
   ...

---------------------------------------------------------
 93:              SYS_select 5s 4m
---------------------------------------------------------
Syscall param select(n) contains uninitialised byte(s)
   ...

Syscall param select(readfds) contains uninitialised byte(s)
   ...

Syscall param select(writefds) contains uninitialised byte(s)
   ...

Syscall param select(exceptfds) contains uninitialised byte(s)
   ...

Syscall param select(timeout) contains uninitialised byte(s)
   ...

Syscall param select(readfds) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param select(writefds) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param select(exceptfds) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param select(timeout) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 95:               SYS_fsync 1s 0m
---------------------------------------------------------
Syscall param fsync(fd) contains uninitialised byte(s)
   ...

---------------------------------------------------------
 96:         SYS_setpriority 3s 0m
---------------------------------------------------------
Syscall param setpriority(which) contains uninitialised byte(s)
   ...

Syscall param setpriority(who) contains uninitialised byte(s)
   ...

Syscall param setpriority(prio) contains uninitialised byte(s)
   ...

---------------------------------------------------------
 97:              SYS_socket 3s 0m
---------------------------------------------------------
Syscall param socket(domain) contains uninitialised byte(s)
   ...

Syscall param socket(type) contains uninitialised byte(s)
   ...

Syscall param socket(protocol) contains uninitialised byte(s)
   ...

---------------------------------------------------------
 98:             SYS_connect 3s 0m
---------------------------------------------------------
Syscall param connect(sockfd) contains uninitialised byte(s)
   ...

Syscall param connect(serv_addr) contains uninitialised byte(s)
   ...

Syscall param connect(addrlen) contains uninitialised byte(s)
   ...

---------------------------------------------------------
100:         SYS_getpriority 2s 0m
---------------------------------------------------------
Syscall param getpriority(which) contains uninitialised byte(s)
   ...

Syscall param getpriority(who) contains uninitialised byte(s)
   ...

---------------------------------------------------------
104:                SYS_bind 3s 0m
---------------------------------------------------------
Syscall param bind(sockfd) contains uninitialised byte(s)
   ...

Syscall param bind(my_addr) contains uninitialised byte(s)
   ...

Syscall param bind(addrlen) contains uninitialised byte(s)
   ...

---------------------------------------------------------
105:          SYS_setsockopt 5s 0m
---------------------------------------------------------
Syscall param setsockopt(s) contains uninitialised byte(s)
   ...

Syscall param setsockopt(level) contains uninitialised byte(s)
   ...

Syscall param setsockopt(optname) contains uninitialised byte(s)
   ...

Syscall param setsockopt(optval) contains uninitialised byte(s)
   ...

Syscall param setsockopt(optlen) contains uninitialised byte(s)
   ...

---------------------------------------------------------
106:              SYS_listen 2s 0m
---------------------------------------------------------
Syscall param listen(s) contains uninitialised byte(s)
   ...

Syscall param listen(backlog) contains uninitialised byte(s)
   ...

---------------------------------------------------------
116:        SYS_gettimeofday 2s 2m
---------------------------------------------------------
Syscall param gettimeofday(tv) contains uninitialised byte(s)
   ...

Syscall param gettimeofday(tz) contains uninitialised byte(s)
   ...

Syscall param gettimeofday(tv) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param gettimeofday(tz) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
117:           SYS_getrusage 2s 1m
---------------------------------------------------------
Syscall param getrusage(who) contains uninitialised byte(s)
   ...

Syscall param getrusage(usage) contains uninitialised byte(s)
   ...

Syscall param getrusage(usage) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
105:          SYS_setsockopt 5s 1m
---------------------------------------------------------
Syscall param setsockopt(s) contains uninitialised byte(s)
   ...

Syscall param setsockopt(level) contains uninitialised byte(s)
   ...

Syscall param setsockopt(optname) contains uninitialised byte(s)
   ...

Syscall param setsockopt(optval) contains uninitialised byte(s)
   ...

Syscall param setsockopt(optlen) contains uninitialised byte(s)
   ...

---------------------------------------------------------
120:               SYS_readv 3s 1m
---------------------------------------------------------
Syscall param readv(fd) contains uninitialised byte(s)
   ...

Syscall param readv(vector) contains uninitialised byte(s)
   ...

Syscall param readv(count) contains uninitialised byte(s)
   ...

Syscall param readv(vector) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
121:              SYS_writev 3s 1m
---------------------------------------------------------
Syscall param writev(fd) contains uninitialised byte(s)
   ...

Syscall param writev(vector) contains uninitialised byte(s)
   ...

Syscall param writev(count) contains uninitialised byte(s)
   ...

Syscall param writev(vector) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
122:        SYS_settimeofday 2s 2m
---------------------------------------------------------
Syscall param settimeofday(tv) contains uninitialised byte(s)
   ...

Syscall param settimeofday(tz) contains uninitialised byte(s)
   ...

Syscall param settimeofday(tv) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param settimeofday(tz) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
123:              SYS_fchown 3s 0m
---------------------------------------------------------
Syscall param fchown(fd) contains uninitialised byte(s)
   ...

Syscall param fchown(owner) contains uninitialised byte(s)
   ...

Syscall param fchown(group) contains uninitialised byte(s)
   ...

---------------------------------------------------------
124:              SYS_fchmod 2s 0m
---------------------------------------------------------
Syscall param fchmod(fildes) contains uninitialised byte(s)
   ...

Syscall param fchmod(mode) contains uninitialised byte(s)
   ...

---------------------------------------------------------
126:            SYS_setreuid 2s 0m
---------------------------------------------------------
Syscall param setreuid(ruid) contains uninitialised byte(s)
   ...

Syscall param setreuid(euid) contains uninitialised byte(s)
   ...

---------------------------------------------------------
127:            SYS_setregid 2s 0m
---------------------------------------------------------
Syscall param setregid(rgid) contains uninitialised byte(s)
   ...

Syscall param setregid(egid) contains uninitialised byte(s)
   ...

---------------------------------------------------------
128:              SYS_rename 2s 2m
---------------------------------------------------------
Syscall param rename(oldpath) contains uninitialised byte(s)
   ...

Syscall param rename(newpath) contains uninitialised byte(s)
   ...

Syscall param rename(oldpath) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param rename(newpath) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
131:               SYS_flock 2s 0m
---------------------------------------------------------
Syscall param flock(fd) contains uninitialised byte(s)
   ...

Syscall param flock(operation) contains uninitialised byte(s)
   ...

---------------------------------------------------------
132:              SYS_mkfifo 2s 1m
---------------------------------------------------------
Syscall param mkfifo(pathname) contains uninitialised byte(s)
   ...

Syscall param mkfifo(mode) contains uninitialised byte(s)
   ...

Syscall param mkfifo(pathname) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
133:              SYS_sendto 6s 0m
---------------------------------------------------------
Syscall param sendto(s) contains uninitialised byte(s)
   ...

Syscall param sendto(msg) contains uninitialised byte(s)
   ...

Syscall param sendto(len) contains uninitialised byte(s)
   ...

Syscall param sendto(flags) contains uninitialised byte(s)
   ...

Syscall param sendto(to) contains uninitialised byte(s)
   ...

---------------------------------------------------------
135:          SYS_socketpair 4s 1m
---------------------------------------------------------
Syscall param socketpair(d) contains uninitialised byte(s)
   ...

Syscall param socketpair(type) contains uninitialised byte(s)
   ...

Syscall param socketpair(protocol) contains uninitialised byte(s)
   ...

Syscall param socketpair(sv) contains uninitialised byte(s)
   ...

Syscall param socketcall.socketpair(sv) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
136:               SYS_mkdir 2s 1m
---------------------------------------------------------
Syscall param mkdir(pathname) contains uninitialised byte(s)
   ...

Syscall param mkdir(mode) contains uninitialised byte(s)
   ...

Syscall param mkdir(pathname) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
137:               SYS_rmdir 1s 1m
---------------------------------------------------------
Syscall param rmdir(pathname) contains uninitialised byte(s)
   ...

Syscall param rmdir(pathname) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
138:              SYS_utimes 2s 2m
---------------------------------------------------------
Syscall param utimes(filename) contains uninitialised byte(s)
   ...

Syscall param utimes(tvp) contains uninitialised byte(s)
   ...

Syscall param utimes(filename) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param utimes(tvp[0]) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param utimes(tvp[1]) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
140:             SYS_adjtime 2s 1m
---------------------------------------------------------
Syscall param adjtime(delta) contains uninitialised byte(s)
   ...

Syscall param adjtime(olddelta) contains uninitialised byte(s)
   ...

Syscall param adjtime(delta) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
147:              SYS_setsid 0s 0m
---------------------------------------------------------
---------------------------------------------------------
148:            SYS_quotactl (Q_QUOTAOFF) 2s 0m
---------------------------------------------------------
Syscall param quotactl(path) contains uninitialised byte(s)
   ...

Syscall param quotactl(cmd) contains uninitialised byte(s)
   ...

---------------------------------------------------------
148:            SYS_quotactl (Q_QUOTAON) 4s 2m
---------------------------------------------------------
Syscall param quotactl(path) contains uninitialised byte(s)
   ...

Syscall param quotactl(cmd) contains uninitialised byte(s)
   ...

Syscall param quotactl(id) contains uninitialised byte(s)
   ...

Syscall param quotactl(addr) contains uninitialised byte(s)
   ...

Syscall param quotactl(path) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
160:              SYS_lgetfh 2s 2m
---------------------------------------------------------
Syscall param lgetfh(path) contains uninitialised byte(s)
   ...

Syscall param lgetfh(fhp) contains uninitialised byte(s)
   ...

Syscall param lgetfh(path) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param lgetfh(fhp) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
161:               SYS_getfh 2s 2m
---------------------------------------------------------
Syscall param getfh(path) contains uninitialised byte(s)
   ...

Syscall param getfh(fhp) contains uninitialised byte(s)
   ...

Syscall param getfh(path) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param getfh(fhp) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
165:             SYS_sysarch 2s 1m
---------------------------------------------------------
Syscall param sysarch(number) contains uninitialised byte(s)
   ...

Syscall param sysarch(args) contains uninitialised byte(s)
   ...

Syscall param amd64_get_fsbase(basep) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
165:             SYS_sysarch 2s 0m
---------------------------------------------------------
Syscall param sysarch(number) contains uninitialised byte(s)
   ...

Syscall param sysarch(args) contains uninitialised byte(s)
   ...

---------------------------------------------------------
166:              SYS_rtprio (GET) 3s 1m
---------------------------------------------------------
Syscall param rtprio(function) contains uninitialised byte(s)
   ...

Syscall param rtprio(pid) contains uninitialised byte(s)
   ...

Syscall param rtprio(rtp) contains uninitialised byte(s)
   ...

Syscall param rtprio(rtp#lookup) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
166:              SYS_rtprio (SET) 3s 1m
---------------------------------------------------------
Syscall param rtprio(function) contains uninitialised byte(s)
   ...

Syscall param rtprio(pid) contains uninitialised byte(s)
   ...

Syscall param rtprio(rtp) contains uninitialised byte(s)
   ...

Syscall param rtprio(rtp#set) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
181:              SYS_setgid 1s 0m
---------------------------------------------------------
Syscall param setgid(gid) contains uninitialised byte(s)
   ...

---------------------------------------------------------
182:             SYS_setegid 1s 0m
---------------------------------------------------------
Syscall param setegid(gid) contains uninitialised byte(s)
   ...

---------------------------------------------------------
183:             SYS_seteuid 1s 0m
---------------------------------------------------------
Syscall param seteuid(uid) contains uninitialised byte(s)
   ...

---------------------------------------------------------
188:      SYS_freebsd11_stat 2s 2m
---------------------------------------------------------
Syscall param stat(file_name) contains uninitialised byte(s)
   ...

Syscall param stat(buf) contains uninitialised byte(s)
   ...

Syscall param stat(file_name) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param stat(buf) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
189:     SYS_freebsd11_fstat 2s 1m
---------------------------------------------------------
Syscall param fstat(fd) contains uninitialised byte(s)
   ...

Syscall param fstat(buf) contains uninitialised byte(s)
   ...

Syscall param fstat(buf) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
190:     SYS_freebsd11_lstat 2s 2m
---------------------------------------------------------
Syscall param lstat(file_name) contains uninitialised byte(s)
   ...

Syscall param lstat(buf) contains uninitialised byte(s)
   ...

Syscall param lstat(file_name) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param lstat(buf) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
191:            SYS_pathconf 2s 1m
---------------------------------------------------------
Syscall param pathconf(file_name) contains uninitialised byte(s)
   ...

Syscall param pathconf(name) contains uninitialised byte(s)
   ...

Syscall param pathconf(file_name) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
192:           SYS_fpathconf 2s 0m
---------------------------------------------------------
Syscall param fpathconf(fd) contains uninitialised byte(s)
   ...

Syscall param fpathconf(name) contains uninitialised byte(s)
   ...

---------------------------------------------------------
194:           SYS_getrlimit 2s 1m
---------------------------------------------------------
Syscall param getrlimit(resource) contains uninitialised byte(s)
   ...

Syscall param getrlimit(rlim) contains uninitialised byte(s)
   ...

Syscall param getrlimit(rlim) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
195:           SYS_setrlimit 2s 1m
---------------------------------------------------------
Syscall param setrlimit(resource) contains uninitialised byte(s)
   ...

Syscall param setrlimit(rlim) contains uninitialised byte(s)
   ...

Syscall param setrlimit(rlim) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
196:SYS_freebsd11_getdirentries 4s 2m
---------------------------------------------------------
Syscall param getdirentries(fd) contains uninitialised byte(s)
   ...

Syscall param getdirentries(buf) contains uninitialised byte(s)
   ...

Syscall param getdirentries(nbytes) contains uninitialised byte(s)
   ...

Syscall param getdirentries(basep) contains uninitialised byte(s)
   ...

Syscall param getdirentries(buf) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param getdirentries(basep) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
202:            SYS___sysctl (getoldlen) 3s 2m
---------------------------------------------------------
Syscall param __sysctl(name) contains uninitialised byte(s)
   ...

Syscall param __sysctl(namelen) contains uninitialised byte(s)
   ...

Syscall param __sysctl(oldlenp) contains uninitialised byte(s)
   ...

Syscall param sysctl(name) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param sysctl(oldlenp) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
202:            SYS___sysctl (getold) 4s 2m
---------------------------------------------------------
Syscall param __sysctl(name) contains uninitialised byte(s)
   ...

Syscall param __sysctl(namelen) contains uninitialised byte(s)
   ...

Syscall param __sysctl(oldp) contains uninitialised byte(s)
   ...

Syscall param __sysctl(oldlenp) contains uninitialised byte(s)
   ...

Syscall param sysctl(name) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param sysctl(oldlenp) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Warning: Bad oldlenp address 0x........ in syctl
---------------------------------------------------------
202:            SYS___sysctl (putnew) 4s 2m
---------------------------------------------------------
Syscall param __sysctl(name) contains uninitialised byte(s)
   ...

Syscall param __sysctl(namelen) contains uninitialised byte(s)
   ...

Syscall param __sysctl(newp) contains uninitialised byte(s)
   ...

Syscall param sysctl(name) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param sysctl(newp) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
203:               SYS_mlock 2s 0m
---------------------------------------------------------
Syscall param mlock(addr) contains uninitialised byte(s)
   ...

Syscall param mlock(len) contains uninitialised byte(s)
   ...

---------------------------------------------------------
204:             SYS_munlock 2s 0m
---------------------------------------------------------
Syscall param munlock(addr) contains uninitialised byte(s)
   ...

Syscall param munlock(len) contains uninitialised byte(s)
   ...

---------------------------------------------------------
205:            SYS_undelete 1s 1m
---------------------------------------------------------
Syscall param undelete(pathname) contains uninitialised byte(s)
   ...

Syscall param undelete(pathname) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
206:             SYS_futimes 2s 0m
---------------------------------------------------------
Syscall param futimes(fd) contains uninitialised byte(s)
   ...

Syscall param futimes(tvp) contains uninitialised byte(s)
   ...

---------------------------------------------------------
207:             SYS_getpgid 1s 0m
---------------------------------------------------------
Syscall param getpgid(pid) contains uninitialised byte(s)
   ...

---------------------------------------------------------
209:                SYS_poll 3s 3m
---------------------------------------------------------
Syscall param poll(ufds) contains uninitialised byte(s)
   ...

Syscall param poll(nfds) contains uninitialised byte(s)
   ...

Syscall param poll(timeout) contains uninitialised byte(s)
   ...

Syscall param poll(ufds.fd) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param poll(ufds.events) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param poll(ufds.revents) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
220:   SYS_freebsd7___semctl 4s 1m
---------------------------------------------------------
Syscall param semctl(semid) contains uninitialised byte(s)
   ...

Syscall param semctl(semnum) contains uninitialised byte(s)
   ...

Syscall param semctl(cmd) contains uninitialised byte(s)
   ...

Syscall param semctl(arg) contains uninitialised byte(s)
   ...

Syscall param semctl(IPC_INFO, arg.buf) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
221:              SYS_semget 3s 0m
---------------------------------------------------------
Syscall param semget(key) contains uninitialised byte(s)
   ...

Syscall param semget(nsems) contains uninitialised byte(s)
   ...

Syscall param semget(semflg) contains uninitialised byte(s)
   ...

---------------------------------------------------------
222:               SYS_semop 3s 0m
---------------------------------------------------------
Syscall param semop(semid) contains uninitialised byte(s)
   ...

Syscall param semop(sops) contains uninitialised byte(s)
   ...

Syscall param semop(nsoops) contains uninitialised byte(s)
   ...

---------------------------------------------------------
224:     SYS_freebsd7_msgctl (set) 3s 1m
---------------------------------------------------------
Syscall param msgctl(msqid) contains uninitialised byte(s)
   ...

Syscall param msgctl(cmd) contains uninitialised byte(s)
   ...

Syscall param msgctl(buf) contains uninitialised byte(s)
   ...

Syscall param msgctl(IPC_SET, buf) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
224:     SYS_freebsd7_msgctl (stat) 3s 1m
---------------------------------------------------------
Syscall param msgctl(msqid) contains uninitialised byte(s)
   ...

Syscall param msgctl(cmd) contains uninitialised byte(s)
   ...

Syscall param msgctl(buf) contains uninitialised byte(s)
   ...

Syscall param msgctl(IPC_STAT, buf) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
225:              SYS_msgget 2s 0m
---------------------------------------------------------
Syscall param msgget(key) contains uninitialised byte(s)
   ...

Syscall param msgget(msgflg) contains uninitialised byte(s)
   ...

---------------------------------------------------------
226:              SYS_msgsnd 4s 1m
---------------------------------------------------------
Syscall param msgsnd(msqid) contains uninitialised byte(s)
   ...

Syscall param msgsnd(msgp) contains uninitialised byte(s)
   ...

Syscall param msgsnd(msgsz) contains uninitialised byte(s)
   ...

Syscall param msgsnd(msgflg) contains uninitialised byte(s)
   ...

Syscall param msgsnd(msgp->mtype) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
227:              SYS_msgrcv 4s 1m
---------------------------------------------------------
Syscall param msgrcv(msqid) contains uninitialised byte(s)
   ...

Syscall param msgrcv(msgp) contains uninitialised byte(s)
   ...

Syscall param msgrcv(msgsz) contains uninitialised byte(s)
   ...

Syscall param msgrcv(msgtyp) contains uninitialised byte(s)
   ...

Syscall param msgrcv(msgp->mtype) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
228:               SYS_shmat 3s 0m
---------------------------------------------------------
Syscall param shmat(shmid) contains uninitialised byte(s)
   ...

Syscall param shmat(shmaddr) contains uninitialised byte(s)
   ...

Syscall param shmat(shmflg) contains uninitialised byte(s)
   ...

---------------------------------------------------------
229:     SYS_freebsd7_shmctl 3s 0m
---------------------------------------------------------
Syscall param shmctl(shmid) contains uninitialised byte(s)
   ...

Syscall param shmctl(cmd) contains uninitialised byte(s)
   ...

Syscall param shmctl(buf) contains uninitialised byte(s)
   ...

---------------------------------------------------------
230:               SYS_shmdt 1s 0m
---------------------------------------------------------
Syscall param shmdt(shmaddr) contains uninitialised byte(s)
   ...

---------------------------------------------------------
231:              SYS_shmget 3s 0m
---------------------------------------------------------
Syscall param shmget(key) contains uninitialised byte(s)
   ...

Syscall param shmget(size) contains uninitialised byte(s)
   ...

Syscall param shmget(shmflg) contains uninitialised byte(s)
   ...

---------------------------------------------------------
232:       SYS_clock_gettime 2s 1m
---------------------------------------------------------
Syscall param clock_settime(clk_id) contains uninitialised byte(s)
   ...

Syscall param clock_settime(tp) contains uninitialised byte(s)
   ...

Syscall param clock_settime(tp) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
233:       SYS_clock_settime 2s 1m
---------------------------------------------------------
Syscall param clock_settime(clk_id) contains uninitialised byte(s)
   ...

Syscall param clock_settime(tp) contains uninitialised byte(s)
   ...

Syscall param clock_settime(tp) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
234:        SYS_clock_getres 2s 1m
---------------------------------------------------------
Syscall param clock_getres(clk_id) contains uninitialised byte(s)
   ...

Syscall param clock_getres(res) contains uninitialised byte(s)
   ...

Syscall param clock_getres(res) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
240:           SYS_nanosleep 2s 2m
---------------------------------------------------------
Syscall param nanosleep(req) contains uninitialised byte(s)
   ...

Syscall param nanosleep(rem) contains uninitialised byte(s)
   ...

Syscall param nanosleep(req) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param nanosleep(rem) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
497:            SYS_mkfifoat 3s 1m
---------------------------------------------------------
Syscall param mkfifoat(fd) contains uninitialised byte(s)
   ...

Syscall param mkfifoat(path) contains uninitialised byte(s)
   ...

Syscall param mkfifoat(mode) contains uninitialised byte(s)
   ...

Syscall param mkfifoat(path) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
564:             SYS_getfhat 4s 2m
---------------------------------------------------------
Syscall param getfhat(fd) contains uninitialised byte(s)
   ...

Syscall param getfhat(path) contains uninitialised byte(s)
   ...

Syscall param getfhat(fhp) contains uninitialised byte(s)
   ...

Syscall param getfhat(flag) contains uninitialised byte(s)
   ...

Syscall param getfhat(path) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param getfhat(fhp) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

