---------------------------------------------------------
  1:                SYS_exit below
---------------------------------------------------------
---------------------------------------------------------
  2:                SYS_fork @todo
---------------------------------------------------------
---------------------------------------------------------
  3:                SYS_read 1+3s 0m
---------------------------------------------------------
Syscall param (syscallno) contains uninitialised byte(s)
   ...

Syscall param read(buf) contains uninitialised byte(s)
   ...

Syscall param read(count) contains uninitialised byte(s)
   ...

Syscall param read(buf) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
  4:               SYS_write 3s 1m
---------------------------------------------------------
Syscall param write(fd) contains uninitialised byte(s)
   ...

Syscall param write(buf) contains uninitialised byte(s)
   ...

Syscall param write(count) contains uninitialised byte(s)
   ...

Syscall param write(buf) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
  5:                SYS_open (2-args) 2s 1m
---------------------------------------------------------
Syscall param open(filename) contains uninitialised byte(s)
   ...

Syscall param open(flags) contains uninitialised byte(s)
   ...

Syscall param open(filename) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
  5:                SYS_open (3-args) 1s 0m
---------------------------------------------------------
Syscall param open(mode) contains uninitialised byte(s)
   ...

---------------------------------------------------------
  6:               SYS_close 1s 0m
---------------------------------------------------------
Syscall param close(fd) contains uninitialised byte(s)
   ...

---------------------------------------------------------
  7:               SYS_wait4 4s 2m
---------------------------------------------------------
Syscall param wait4(pid) contains uninitialised byte(s)
   ...

Syscall param wait4(status) contains uninitialised byte(s)
   ...

Syscall param wait4(options) contains uninitialised byte(s)
   ...

Syscall param wait4(rusage) contains uninitialised byte(s)
   ...

Syscall param wait4(status) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param wait4(rusage) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
  9:                SYS_link 2s 2m
---------------------------------------------------------
Syscall param link(oldpath) contains uninitialised byte(s)
   ...

Syscall param link(newpath) contains uninitialised byte(s)
   ...

Syscall param link(oldpath) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param link(newpath) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 10:              SYS_unlink 1s 1m
---------------------------------------------------------
Syscall param unlink(pathname) contains uninitialised byte(s)
   ...

Syscall param unlink(pathname) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 12:               SYS_chdir 1s 1m
---------------------------------------------------------
Syscall param chdir(path) contains uninitialised byte(s)
   ...

Syscall param chdir(path) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 13:              SYS_fchdir 1s 0m
---------------------------------------------------------
Syscall param fchdir(fd) contains uninitialised byte(s)
   ...

---------------------------------------------------------
 14:     SYS_freebsd11_mknod 3s 1m
---------------------------------------------------------
Syscall param mknod(pathname) contains uninitialised byte(s)
   ...

Syscall param mknod(mode) contains uninitialised byte(s)
   ...

Syscall param mknod(dev) contains uninitialised byte(s)
   ...

Syscall param mknod(pathname) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 15:               SYS_chmod 2s 1m
---------------------------------------------------------
Syscall param chmod(path) contains uninitialised byte(s)
   ...

Syscall param chmod(mode) contains uninitialised byte(s)
   ...

Syscall param chmod(path) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 16:               SYS_chown 3s 1m
---------------------------------------------------------
Syscall param chown(path) contains uninitialised byte(s)
   ...

Syscall param chown(owner) contains uninitialised byte(s)
   ...

Syscall param chown(group) contains uninitialised byte(s)
   ...

Syscall param chown(path) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 17:               SYS_break ni
---------------------------------------------------------
---------------------------------------------------------
 20:              SYS_getpid 0s 0m
---------------------------------------------------------
